language: php

php:
  - 5.3.0
  - 5.3
  - 5.4
  - 5.5
services: mysql
before_script:
  - mysql -u root -p -h 127.0.0.1 -e 'create database dimensions_test;'
  - composer install --dev --prefer-source
  - mysql -u root -p -h 127.0.0.1 < structure.sql

script: phpunit --bootstrap tests/bootstrap.php --configuration tests/configuration.xml