<?php
namespace DBRisinajumi\Dimensions;

/**
 * Test class for Period.
 * Generated by PHPUnit on 2013-02-02 at 16:51:52.
 */
class PeriodTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Period
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $Database = new \mysqli(TEST_DB_HOST, TEST_DB_USER, TEST_DB_PASSWORD, TEST_DB);
        $this->object = new Period($Database);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetPeriodLengthData().
     */
    public function testGetPeriodLengthData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
